version: '3'

services:
  db:
    image: postgres:latest
    container_name: blog_db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: blog
    volumes:
      - blog_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  blog_db_data:
    driver: local